---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: korrals.kushion.agilestacks.com
spec:
  group: kushion.agilestacks.com
  names:
    kind: Korral
    listKind: KorralList
    plural: korrals
    singular: korral
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Korral is the Schema for the korrals API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KorralSpec defines the desired state of Korral on a Kubernetes cluster
            properties:
              domain:
                type: string
              kubernetes:
                description: Kubernetes API connection parameters
                properties:
                  api:
                    properties:
                      caCert:
                        type: string
                      clientCert:
                        type: string
                      clientKey:
                        type: string
                      endpoint:
                        type: string
                      token:
                        type: string
                    required:
                    - endpoint
                    type: object
                required:
                - api
                type: object
              options:
                description: Options for Operator fine-tuning
                properties:
                  korral:
                    properties:
                      install:
                        type: boolean
                    required:
                    - install
                    type: object
                required:
                - korral
                type: object
            required:
            - domain
            - kubernetes
            type: object
          status:
            description: KorralStatus defines the observed state of Korral
            properties:
              korral:
                type: string
              prometheus:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
