apiVersion: kushion.agilestacks.com/v1
kind: Cluster
metadata:
  name: Arkadi Dev
spec:
  domain: arkadi.dev.superhub.io
  kubernetes:
    api:
      endpoint: https://FA9909D116A618A1F104E8AFC8D990AE.gr7.us-east-2.eks.amazonaws.com
